name: valid_word_database
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  path: ^1.8.0
  objectbox: ^1.6.2
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.0.0
  objectbox_generator: any
  lints: ^2.0.0
  test: ^1.16.0
